---
ise_device:
  host_ip: 192.168.1.21 #10.10.20.77
  base64_auth: Basic YWRtaW46UEBzc3cwcmQxMjM=

# the following info is not required for retrieving data from Cisco ISE
excel:
  excel_file: ./cisco_ise_spreadsheet.xlsx
  sheet_name: Authz_Rule
  rows_range:
    start: 1
    end: 30